// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTTIC32DObjjUM_dtzlDELztO0Xhqq1c',
    appId: '1:112386970932:web:6abb776a17673c47dd8161',
    messagingSenderId: '112386970932',
    projectId: 'total-x-8f3c2',
    authDomain: 'total-x-8f3c2.firebaseapp.com',
    storageBucket: 'total-x-8f3c2.appspot.com',
    measurementId: 'G-ZGE80LS6ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoPRzGl6xjci7VMqLF6rSuKP3jQfy3D4',
    appId: '1:112386970932:android:bec5c166deb1c5fadd8161',
    messagingSenderId: '112386970932',
    projectId: 'total-x-8f3c2',
    storageBucket: 'total-x-8f3c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-Q7BYyPSGbKd_oWbKd651QKNZMcRrmE',
    appId: '1:112386970932:ios:89c90eedcfa94b47dd8161',
    messagingSenderId: '112386970932',
    projectId: 'total-x-8f3c2',
    storageBucket: 'total-x-8f3c2.appspot.com',
    iosBundleId: 'com.example.totalxMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-Q7BYyPSGbKd_oWbKd651QKNZMcRrmE',
    appId: '1:112386970932:ios:89c90eedcfa94b47dd8161',
    messagingSenderId: '112386970932',
    projectId: 'total-x-8f3c2',
    storageBucket: 'total-x-8f3c2.appspot.com',
    iosBundleId: 'com.example.totalxMachineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTTIC32DObjjUM_dtzlDELztO0Xhqq1c',
    appId: '1:112386970932:web:2c674d9fcd8da20ddd8161',
    messagingSenderId: '112386970932',
    projectId: 'total-x-8f3c2',
    authDomain: 'total-x-8f3c2.firebaseapp.com',
    storageBucket: 'total-x-8f3c2.appspot.com',
    measurementId: 'G-7TLC13GDBJ',
  );
}
